#!/bin/bash          
echo "background script in okaapi/lib"
echo "executed by user --" $USER "--"

cd /var/rails/okaapi/lib

pwd

/usr/local/bin/ruby okaapi_background.rb

echo "okaapi_background done"

