#!/bin/bash          
echo "background script in okaapi/lib"
echo "executed by user --" $USER "--"

cd /var/rails/okaapi/lib
#on wien#cd /home/wido/okaapi/lib

pwd

/usr/bin/ruby okaapi_background.rb
#on wien#ruby okaapi_background.rb

echo "okaapi_background done"

/usr/bin/ruby camera_background.rb
#on wien#ruby camera_background.rb

echo "camera background done"

