#!/bin/bash          
echo "background script in okaapi/lib"

cd /var/rails/okaapi/lib
#on wien#cd /home/wido/okaapi/lib

pwd

/usr/local/bin/ruby okaapi_background.rb
#on wien#ruby okaapi_background.rb

echo " "

/usr/local/bin/ruby camera_background.rb
#on wien#ruby camera_background.rb

echo " "

