login: &login
  adapter: mysql
  host: localhost
  username: okaapi
  password: 0kap1
  encoding: utf8
  
development:
  database: okaapi2
  <<: *login

production:
  database: okaapi2	
  <<: *login

test:
  database: okaapi2_test
  <<: *login
